// Code generated by "stringer -type=SensorType"; DO NOT EDIT.

package main

import "strconv"

const _SensorType_name = "ST_VBATST_VCCST_STS31_TEMPST_BME680ST_BME280ST_CCS811ST_APDS9200ST_SOUNDPRESSUREST_PORTINPUTST_LSM9DS1TR_MAGST_LSM9DS1TR_ACCST_LSM9DS1TR_GYROST_MAX_MARKER"

var _SensorType_index = [...]uint8{0, 7, 13, 26, 35, 44, 53, 64, 80, 92, 108, 124, 141, 154}

func (i SensorType) String() string {
	if i < 0 || i >= SensorType(len(_SensorType_index)-1) {
		return "SensorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SensorType_name[_SensorType_index[i]:_SensorType_index[i+1]]
}
