// Code generated by "stringer -type=sensorType"; DO NOT EDIT.

package main

import "strconv"

const _sensorType_name = "stVBATstVCCstSTS31TEMPstBME680stBME280stCCS811stAPDS9200stSOUNDPRESSUREstPORTINPUTstLSM9DS1TRMAGstLSM9DS1TRACCstLSM9DS1TRGYROstMAXMARKER"

var _sensorType_index = [...]uint8{0, 6, 11, 22, 30, 38, 46, 56, 71, 82, 96, 110, 125, 136}

func (i sensorType) String() string {
	if i < 0 || i >= sensorType(len(_sensorType_index)-1) {
		return "sensorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _sensorType_name[_sensorType_index[i]:_sensorType_index[i+1]]
}
